# 하루 세션 제한
DAILY_SESSION_LIMIT = 3

# 토의 최대 라운드
MAX_DISCUSSION_ROUNDS = 10

# 레벨 조정 임계값 (최근 N 세션 평균 점수 기준)
LEVEL_UP_THRESHOLD = 8.0
LEVEL_DOWN_THRESHOLD = 5.0
MIN_LEVEL = 1
MAX_LEVEL = 3
SESSIONS_FOR_LEVEL_ADJUST = 3

# 학생 JWT 토큰 만료일
STUDENT_TOKEN_EXPIRE_DAYS = 30

# 세션 타임아웃 (분)
SESSION_TIMEOUT_MINUTES = 60
